### PR TITLE
feat : added reverse number method

### PR DESCRIPTION
**Pull request by dev-madhurendra**
[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### Checklist:

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new JavaScript files are placed inside an existing directory.
- [x] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [x] All new algorithms have a URL in their comments that points to Wikipedia or another similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by appgurueu — APPROVED** [review]

**Comment by raklaptudirm** [comment]
@appgurueu I think this algorithm falls in the trivial category that we discussed in the discord previously, so I don't think it will be a good addition to the repo. What is your opinion?

**Comment by appgurueu** [comment]
Well it is pretty trivial, but I think it is useful to demonstrate the split-transform-join pattern for working around the immutability of strings in JavaScript.

Arguably this shouldn't be called "reverse number" though - it isn't really specific to numbers - but it should be ["reverse string"](https://github.com/TheAlgorithms/JavaScript/blob/master/String/ReverseString.js) which we already have (but not using JS's `reverse`, which would be more concise). I missed this in my review.

@dev-madhurendra please shorten the existing linear time string reversal code to a one-liner.

**Comment by dev-madhurendra** [comment]
> Well it is pretty trivial, but I think it is useful to demonstrate the split-transform-join pattern for working around the immutability of strings in JavaScript.
> 
> Arguably this shouldn't be called "reverse number" though - it isn't really specific to numbers - but it should be ["reverse string"](https://github.com/TheAlgorithms/JavaScript/blob/master/String/ReverseString.js) which we already have (but not using JS's `reverse`, which would be more concise). I missed this in my review.
> 
> @dev-madhurendra please just shorten the existing linear time string reversal code to a one-liner.

@appgurueu It is already one linear 

> Well it is pretty trivial, but I think it is useful to demonstrate the split-transform-join pattern for working around the immutability of strings in JavaScript.
> 
> Arguably this shouldn't be called "reverse number" though - it isn't really specific to numbers - but it should be ["reverse string"](https://github.com/TheAlgorithms/JavaScript/blob/master/String/ReverseString.js) which we already have (but not using JS's `reverse`, which would be more concise). I missed this in my review.
> 
> @dev-madhurendra please just shorten the existing linear time string reversal code to a one-liner.

@appgurueu I think it is already one linear.

**Comment by appgurueu** [comment]
It is already linear-time, but it is not a *one-liner*: It is needlessly verbose as it manually does the array reversal rather than using JS's `reverse` built-in. It should be just `str.split('').reverse().join('')` (or `[...str].reverse().join('')`).

**Pull request closed without merging**
