### PR TITLE
chore: add instruction for installing dependencies

### PR DESCRIPTION
**Pull request by abdulfrfr**
…d test some codes and i found out that i needed to run and install jest from npm first, i did and it worked

[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

- [ ] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [X] Documentation change?

### Checklist:

- [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [X] This pull request is all my own work -- I have not plagiarized.
- [ ] I know that pull requests will not be merged if they fail the automated tests.
- [ ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [X] All new JavaScript files are placed inside an existing directory.
- [ ] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by raklaptudirm** [comment]
Seems unnecessary to me, you automatically install jest when you run npm install.

**Review by appgurueu — CHANGES_REQUESTED** [review]
Please change this to recommend installation of all deps through `npm install`

**Comment by abdulfrfr** [comment]
> Please change this to recommend installation of all deps through `npm install`



Okay, I’ll do that.

**Comment by abdulfrfr** [comment]
> Seems unnecessary to me, you automatically install jest when you run npm install.


someone might not know he or she has to run the npm install, as a newbie, it was a challenge for me and i had it discovered to i thought it would be of clarification to other newbies.

**Review by raklaptudirm — DISMISSED** [review]
Guess we can add that.

**Comment by abdulfrfr** [comment]
> Guess we can add that.

Alright thanks.

**Review by appgurueu — APPROVED** [review]

**Review by raklaptudirm — APPROVED** [review]

**Pull request merged**
