### PR TITLE
[DO NOT MERGE before adding the token] chore: update `codecov-action` to `v4`

### PR DESCRIPTION
**Pull request by vil02**
[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

Same as TheAlgorithms/Rust#670 - it contains the description of the problem.

Before merging, please add the token from https://app.codecov.io/gh/TheAlgorithms/JavaScript/settings as `CODECOV_TOKEN` into the repo secrets.

### Checklist:

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.

### CODE REVIEW

**Comment by appgurueu** [comment]
It seems that in order to add the token, I would have to be logged in (on the codecov site) to access https://app.codecov.io/gh/TheAlgorithms/JavaScript/settings ? I'm slightly uncomfortable with this as it requests permission to "act on my behalf":

Screenshot from 2024-02-02 20-47-06

**Comment by vil02** [comment]
> It seems that in order to add the token, I would have to be logged in (on the codecov site) to access https://app.codecov.io/gh/TheAlgorithms/JavaScript/settings ? 

Yes.

> I'm slightly uncomfortable with this as it requests permission to "act on my behalf":

I agree.

**Comment by appgurueu** [comment]
I bit the bullet and authorized CodeCov to obtain the token, but it turns out that I can't edit repo secrets since I do not have "admin" permissions. This will require @Panquesito7 or @AnupKumarPanwar I believe.

**Comment by raklaptudirm** [comment]
@appgurueu You should have admin access to the repository now

**Comment by vil02** [comment]
Just in case: please make sure that `CODECOV_TOKEN` is also added to the dependabot secrets (6e27235fb75298833448ba1b23e5178f7eea2290 adds dependabot).

**Comment by appgurueu** [comment]
> Just in case: please make sure that `CODECOV_TOKEN` is also added to the dependabot secrets ([6e27235](https://github.com/TheAlgorithms/JavaScript/commit/6e27235fb75298833448ba1b23e5178f7eea2290) adds dependabot).

Why would dependabot need the codecov token? It seems to work as-is: https://app.codecov.io/github/TheAlgorithms/JavaScript/commit/9010481c2930d65621f18f41c216f29fceaa8807

**Comment by vil02** [comment]
Without it, the `UploadCoverageReport` will fail for each PR created by dependabot.

**Pull request merged**
