### PR TITLE
Added Tree Sort algorithms

### PR DESCRIPTION
**Pull request by sonechca**
# Welcome to JavaScript community

### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new JavaScript files are placed inside an existing directory.
* [x] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by ruppysuppy — CHANGES_REQUESTED** [review]
Make sure that the checks pass, its most probably failing due to improper styling. Use `standard` as mentioned in [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md)

**Comment by cclauss** [comment]
Run `standard --fix` to automatically fix some problems.

**Comment by marsonya** [comment]
I think this may be abandoned, but I'll ping one more time, because I think it's great work! @sonechca, could you rebase this and fix the errors?

**Comment by marsonya** [comment]
Please reopen this pull request once you commit the changes requested or make improvements on the code. Thank you for your contributions!

**Comment by cclauss** [comment]
A contributor who does not have write access to the repo (i.e. they are not a maintainer) does not have the rights to reopen a closed pull request.  They would need to open a new PR.

**Comment by marsonya** [comment]
> A contributor who does not have write access to the repo (i.e. they are not a maintainer) does not have the rights to reopen a closed pull request. They would need to open a new PR.

I stand corrected. Have edited the comment to reflect the correct information.

**Pull request closed without merging**
