### PR TITLE
algorithm: letter combinations

### PR DESCRIPTION
**Pull request by hiitesh1127**
[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

`It is one of the most common Backtracking Problems asked during interviews`

### Describe your change:

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### Checklist:

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new JavaScript files are placed inside an existing directory.
- [x] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/JavaScript/pull/1209"></a>

### CODE REVIEW

**Review by appgurueu — CHANGES_REQUESTED** [review]
How is this a backtracking problem? At first glance this appears to be a simple combinatorial problem: Finding the cross product of the sets of possible letters for all numbers.

**Comment by hiitesh1127** [comment]
@appgurueu You are correct when there are just two digits in the provided string, but if we analyze the scenario of three digits, we notice that we need to backtrack for the second digit.

**Comment by appgurueu** [comment]
> @appgurueu Sir you are correct when there are just two digits in the provided string, but if we analyze the scenario of three digits, we notice that we need to backtrack for the second digit string.

I wrote the following solution which got accepted in Go:

```go
func letterCombinations(digits string) []string {
    if digits == "" {
        return []string{}
    }
    letters := [8]string{"abc", "def", "ghi", "jkl", "mno", "pqrs", "tuv", "wxyz"}
    res := []string{""}
    for _, digit := range digits {
        nextRes := []string{}
        for _, letter := range letters[digit - '2'] {
            for _, str := range res {
                nextRes = append(nextRes, str + string(letter))
            }
        }
        res = nextRes
    }
    return res
}
```

this problem does not inherently require recursion or backtracking? As said, it's just the cartesian product ${a, b, c} \times {d, e, f} \times {g, h, i}$ f.E. for $123$.

**Comment by hiitesh1127** [comment]
> > @appgurueu Sir you are correct when there are just two digits in the provided string, but if we analyze the scenario of three digits, we notice that we need to backtrack for the second digit string.
> 
> I wrote the following solution which got accepted in Go:
> 
> ```go
> func letterCombinations(digits string) []string {
>     if digits == "" {
>         return []string{}
>     }
>     letters := [8]string{"abc", "def", "ghi", "jkl", "mno", "pqrs", "tuv", "wxyz"}
>     res := []string{""}
>     for _, digit := range digits {
>         nextRes := []string{}
>         for _, letter := range letters[digit - '2'] {
>             for _, str := range res {
>                 nextRes = append(nextRes, str + string(letter))
>             }
>         }
>         res = nextRes
>     }
>     return res
> }
> ```
> 
> this problem does not inherently require recursion or backtracking? As said, it's just the cartesian product {a,b,c}×{d,e,f}×{g,h,i} f.E. for 123.

Okay Sir,
My backtracking approach for this solution is 
we need to backtrack for node no 3's

lettercombination

**Comment by appgurueu** [comment]
> Backtracking is a class of algorithm for finding solutions to some computational problems, notably constraint satisfaction problems, that incrementally builds candidates to the solutions, and abandons a candidate as soon as it determines that the candidate cannot possibly be completed to a valid solution.

\- from https://en.wikipedia.org/wiki/Backtracking

I don't see how this definition is met (if I'm missing something, please explain). All I see is a simple combinatorial algorithm. LeetCode and InterviewBit are probably getting their terminology wrong.

**Comment by hiitesh1127** [comment]
Please review @raklaptudirm

**Comment by hiitesh1127** [comment]
> I guess recursive would be best.

Okay I will update

**Comment by hiitesh1127** [comment]
Done @appgurueu @raklaptudirm

**Review by appgurueu — APPROVED** [review]

**Review by raklaptudirm — APPROVED** [review]

**Pull request merged**
