### PR TITLE
Refactor Maths/Factorial for more minimal side effects.

### PR DESCRIPTION
**Pull request by Eji4h**
# Welcome to JavaScript community

### **Describe your change:**

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new JavaScript files are placed inside an existing directory.
* [x] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by Eji4h** [comment]
@pomkarnath98  Why to don't merge this PR?

**Comment by pomkarnath98** [comment]
Factorial is already there in the list. So we can only merge if it is not present in the list. Hope you understand. 
Thank you

**Comment by Eji4h** [comment]
> Factorial is already there in the list. So we can only merge if it is not present in the list. Hope you understand.
> Thank you

It's already but i'm refactor code to minimal side effects.

**Comment by pomkarnath98** [comment]
Ok, we will get back to you soon. 
But you should mention the #{ISSUE_NO} that your code resolved. And if it's not there you could create one and then mention by stating that the code ia fixing that issue.

**Comment by Eji4h** [comment]
Fixed #503

**Review by marsonya — CHANGES_REQUESTED** [review]
Hey @Eji4h, the refactoring looks good. There one thing that needs changing.
Move the (num > 0) if condition to the end.

It's a general practice to validate the input first and then calculate and return the solution if the input passes validation.

**Review by marsonya — APPROVED** [review]

**Pull request merged**
