### PR TITLE
improve pow function so it can receive negative exponents

### PR DESCRIPTION
**Pull request by farha1**
# Welcome to JavaScript community

[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### **Describe your change:**

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new JavaScript files are placed inside an existing directory.
* [x] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by raklaptudirm — APPROVED** [review]

**Comment by raklaptudirm** [comment]
Looks like our exponent implementation is really slow. Could you change it to an implementation of [Exponentiation by squaring](https://en.wikipedia.org/wiki/Exponentiation_by_squaring)?

**Comment by farha1** [comment]
Okey I will try..

on this PR or make new PR? @raklaptudirm .. Sorry, I am beginner in open source contribution..

**Comment by raklaptudirm** [comment]
If you are going to do it, then close this pr and do it in a new one, in the same file.

**Comment by farha1** [comment]
okey.. thanks..

**Pull request closed without merging**
