### PR TITLE
Syntax update and new Dynamic-programming Algorithm

### PR DESCRIPTION
**Pull request by raklaptudirm**
e0d2e5a: Updated the if condition in leap year detection to include just one if.
0f703a5: Dynamic-programming algorithm that prints the calendar of a provided month.

# Welcome to JavaScript community

[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### **Describe your change:**

* [x] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new JavaScript files are placed inside an existing directory.
* [x] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by marsonya — COMMENTED** [review]
Kindly explain how does this improve the code.
I think the readability is in fact reduced.

**Comment by raklaptudirm** [comment]
@marsonya ,2 ifs were unnecessary for the given situation. If it was to increase the readability, kindly close this request.

**Comment by raklaptudirm** [comment]
The new commit adds a Dynamic-programming algorithm that prints the calendar of a provided month.

**Comment by marsonya** [comment]
> The new commit adds a Dynamic-programming algorithm that prints the calendar of a provided month. Path `Dynamic-algorithms/printMonthCalendar.js`

It's a good contribution. But, it needs to be a seperate PR.

**Review by marsonya — COMMENTED** [review]
Two different works have been mixed in this PR. The first one is not required but the Dynamic Programming Algorithm might be a good addition. 
That said, the second contribution needs to be a seperate PR.

I am closing this issue.

**Comment by raklaptudirm** [comment]
Ok, thanks for informing me. By the way, the if can be updated still as it is `(year % 100 === 0 && year % 400 === 0)) {` is unnecessary. If it is divisible by 400, it is also divisible by 100. No need to chack that. You can make that change.

**Pull request closed without merging**
