### PR TITLE
Create WiggleSort.js

### PR DESCRIPTION
**Pull request by iMeet07**
Added Wiggle Sort Algorithm

### CODE REVIEW

**Comment by appgurueu** [comment]
Please read [our contribution guidelines](https://github.com/TheAlgorithms/JavaScript/blob/master/CONTRIBUTING.md).

**Comment by iMeet07** [comment]
What's the Issue. Pls elaborate still I m not getting. I already read it.

**Comment by appgurueu** [comment]
* This PR adds both WiggleSort and BitonicSort (that's probably just a mistake).
* Comments (for exported functions/classes) should use JSDoc. `WiggleSort` should be exported to begin with.
* **Algorithms need to be tested using Jest tests** (this is the main issue). There should be no side effects (e.g. examples with `console.log`) left in the code.

**Comment by iMeet07** [comment]
I have dine the changes do check it please.

**Pull request closed without merging**
