### PR TITLE
More accurate error message at `IsDivisible`

### PR DESCRIPTION
**Pull request by Rudxain**
[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

- [ ] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

This PR edits the error message in that file (Maths/IsDivisible.js) to be more accurate to its context. Because `Infinity` and `NaN` aren't valid Real numbers.

### Checklist:

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new JavaScript files are placed inside an existing directory.
- [x] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by appgurueu — APPROVED** [review]
(consider lowercasing the `r` from `real`)

**Comment by Rudxain** [comment]
> (consider lowercasing the `r` from `real`)

Why? I thought it was a good idea to make it uppercase to distinguish between "real" (reality) and "Real" (the set of all non-complex rational and irrational numbers). But, for consistency, it may also be a good idea to lowercase it

**Comment by appgurueu** [comment]
> Why? I thought it was a good idea to make it uppercase to distinguish between "real" (reality) and "Real" (the set of all non-complex rational and irrational numbers). But, for consistency, it may also be a good idea to lowercase it

"real number" already is an unambiguous term and thus fine - no need to bend the rules of capitalization to emphasize the "real" property.

**Comment by Rudxain** [comment]
Ok then I'll change it now

**Pull request merged**
