### PR TITLE
Proposal: Clean up CI job a bit

### PR DESCRIPTION
**Pull request by defaude**
relates to #586 and #720

Added npm scripts for doctest and style checking via standard. This allows us to call those directly via npm and not via npx.

The CI job itself is now split into distinct steps (makes it more visible which step failed).

### CODE REVIEW

**Comment by defaude** [comment]
Sweet! The "Continuous Integration" job [looks quite nice now](https://github.com/TheAlgorithms/Javascript/pull/727/checks?check_run_id=3784372350), doesn't it?

**Comment by defaude** [comment]
The job that's updating the DIRECTORY.md file has been cleaned up quite a bit, too. It's now faster and only creates a commit when there's actually a change.

**Comment by raklaptudirm** [comment]
Could you fix the emerged issues?

**Comment by defaude** [comment]
I did not _really_ introduce a new bug - I just applied `standard` to the code and it switched from a double-quoted string to a single-quoted string. The error was there all along, but a fix is done quickly - coming right up :)

**Comment by raklaptudirm** [comment]
@cclauss knows better about these files than me, please wait for their review.

**Review by cclauss — APPROVED** [review]
RSLGTM

**Comment by raklaptudirm** [comment]
@defaude Please resolve the conflicts so that it can be merged.

**Comment by cclauss** [comment]
This job OVERWRITES DIRECTORY.md.

**Comment by defaude** [comment]
The only conflict is the auto-generated DIRECTORY.md - and yes, this job deliberately overwrites this file (and has been doing so for quite some time before my refactoring, after all) ;)

**Pull request merged**
