### PR TITLE
feat: Added string symmetry check algorithm

### PR DESCRIPTION
**Pull request by Nikunj-bisht**
[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

- [X] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### Checklist:

- [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [X] This pull request is all my own work -- I have not plagiarized.
- [X] I know that pull requests will not be merged if they fail the automated tests.
- [X] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [X] All new JavaScript files are placed inside an existing directory.
- [X] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or another similar explanation.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by appgurueu — COMMENTED** [review]
Sorry, but I don't think this algorithm is a good addition. It's pretty much trivial (esp. if seen as check palindrome + check charset) and solves an oddly specific problem.
(Code-wise it's mostly fine though, but should return a bool rather than strings.)

@raklaptudirm thoughts?

**Comment by Nikunj-bisht** [comment]
ok , no issues i will come up with a new algo

**Comment by appgurueu** [comment]
> ok , no issues i will come up with a new algo

My advice: Try to stick to generally useful nontrivial standard algorithms. For example Push-Relabel if you want to implement a network flow algorithm. You will ideally learn more (for this, first fully understand the algorithm, then implement it from scratch / memory) and your contributions will be more interesting and useful.

**Comment by raklaptudirm** [comment]
Closing PR.

**Pull request closed without merging**
