### PR TITLE
OddEvenSort Added

### PR DESCRIPTION
**Pull request by MustafaSalih1993**
# Welcome to JavaScript community

### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new JavaScript files are placed inside an existing directory.
* [x] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by MustafaSalih1993** [comment]
Added sorting algorithm

**Comment by nandanvasudevan** [comment]
Can anyone explain why the below doctest passes? Documentation for JavaScript seems poor.
Notice the **399** in the middle.
```
// > const test = [5, 6, 7, 8, 1, 2, 12, 14, 5, 3, 2, 2]
// > oddEvenSort(test)
// test [1,2,2,2,399,5,5,6,7,8,12,14]
```

The output I get:
```
(node:6277) ExperimentalWarning: The ESM module loader is experimental.
running doctests in test.js...
[ 5, 6, 7, 8, 1, 2, 12, 14, 5, 3, 2, 2 ]
[ 1, 2, 2, 2, 3, 5, 5, 6, 7, 8, 12, 14 ]
.
```
I think it's evaluating with `test`. Is there a syntax I am missing?

**Comment by MustafaSalih1993** [comment]
> ## Test your code
> 
> This works.
> 
> ```
> // > const test = [5, 6, 7, 8, 1, 2, 12, 14, 5, 3, 2, 2]
> // > const result = [ 1, 2, 2, 2, 3, 5, 5, 6, 7, 8, 12, 14 ]
> // > oddEvenSort(test)
> // > (test.every((val, index) => val === result[index]))
> // true
> ```
> 
> ### Output
> 
> ```
> (node:6784) ExperimentalWarning: The ESM module loader is experimental.
> running doctests in test.js...
> [ 5, 6, 7, 8, 1, 2, 12, 14, 5, 3, 2, 2 ]
> [ 1, 2, 2, 2, 3, 5, 5, 6, 7, 8, 12, 14 ]
> .
> ```
> 
> ## Weird DocTest behaviour
> 
> Can anyone explain why the below doctest passes? Documentation for JavaScript seems poor.
> Notice the **399** in the middle.
> 
> ```
> // > const test = [5, 6, 7, 8, 1, 2, 12, 14, 5, 3, 2, 2]
> // > oddEvenSort(test)
> // test [1,2,2,2,399,5,5,6,7,8,12,14]
> ```
> 
> The output I get:
> 
> ```
> (node:6277) ExperimentalWarning: The ESM module loader is experimental.
> running doctests in test.js...
> [ 5, 6, 7, 8, 1, 2, 12, 14, 5, 3, 2, 2 ]
> [ 1, 2, 2, 2, 3, 5, 5, 6, 7, 8, 12, 14 ]
> .
> ```
> 
> I think it's evaluating with `test`. Is there a syntax I am missing?

Already tested, the output for me is:
```javascript
[ 1,  2, 2, 2, 3, 5,  5, 6, 7, 8, 12, 14 ]
```

**Review by klaygueds — APPROVED** [review]
🤔

**Pull request merged**
