### PR TITLE
Added Sleep Sort

### PR DESCRIPTION
**Pull request by saurabhbazzad**
Added the algorithm for Sleep Sort.

### CODE REVIEW

**Comment by cclauss** [comment]
This looks cool to me.  Would you be willing to help us with https://github.com/TheAlgorithms/Javascript/issues/142#issuecomment-627371313 by adding some doctests like https://github.com/TheAlgorithms/Javascript/blob/master/Sorts/BogoSort.js#L6-L13 and then turn them on at https://github.com/TheAlgorithms/Javascript/blob/master/.github/workflows/nodejs.yml#L18

We are trying to understand how difficult it is for new contributors to add tests so your work on this and feedback would be much appreciated.

**Comment by cclauss** [comment]
1. How much does this slow down our CI test runs?
2. Does it properly sort floating point numbers and negative numbers?

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/pull/2352

**Comment by raklaptudirm** [comment]
@cclauss Fixed. See #611

**Pull request merged**
