### PR TITLE
Added file for fetching Github User Information using Github REST API

### PR DESCRIPTION
**Pull request by akkaraju-satvik**
# Welcome to JavaScript community

[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new JavaScript files are placed inside an existing directory.
* [x] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by raklaptudirm** [comment]
This is just an implementation of the Github REST API. It is not considered to be a valid algorithm.

**Comment by akkaraju-satvik** [comment]
hello @raklaptudirm, thank you for the clarification. But would you take a moment to take a look at [this](https://github.com/TheAlgorithms/Javascript/blob/master/Web-Programming/OpenWeatherMaps.js)

**Comment by raklaptudirm** [comment]
This must be from the time when this repository was not properly moderated. Thank you for bringing this to my notice.

**Comment by raklaptudirm** [comment]
See https://github.com/TheAlgorithms/Javascript/commit/63e3403b8b93f1008b3d1ad8c01e2811f229a2fb.

**Comment by akkaraju-satvik** [comment]
and also what kind of algorithms go into web programming? web scrapers?

**Comment by raklaptudirm** [comment]
I have removed that directory. It was not a valid category for algorithms.

**Pull request closed without merging**
