### PR TITLE
Rewrote "Rat in a maze" algorithm + added tests

### PR DESCRIPTION
**Pull request by defaude**
### **Describe your change:**

* [x] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new JavaScript files are placed inside an existing directory.
* [x] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.

### CODE REVIEW

**Comment by pomkarnath98** [comment]
Again @defaude 
If the algorithm is working fine, then no need to modify it. Someone from the team has already approved and merged by reviewing it.
Moreover, don't create test cases for other's files. Try to create PR with a new Algorithm problem.

**Comment by defaude** [comment]
Hi @pomkarnath98 :)

As with #713 , I still think contributing test-cases to already-existing algorithms is valid (and wanted).

Regarding my re-write: True, the existing version worked. It was a bit hard to read, though, and even harder to properly test. So I decided to propose a new implementation that improves a few things:
- more readable (plus more comments)
- better testability
- tiny functional change - the new implementation is loosely based on the original but mixes in the "solution matrix" idea from the example at the [linked article](https://www.geeksforgeeks.org/rat-in-a-maze-backtracking-2/).
- at the same time, introduce a few modern JS syntax things (class syntax, private fields, etc) The reason is: newcomers to this repo might stumble upon this, trying to understand the algorithm itself and are learning something about the language itself at the same time :)

**Comment by defaude** [comment]
Update: I gave @chiranjeev-thapliyal credit as the original implementation's author in the documentation block 👍

**Comment by raklaptudirm** [comment]
@defaude Please format your code with [`standard.js`](https://standardjs.com/).

**Pull request merged**
