### PR TITLE
added an algo which finds unique element in an array

### PR DESCRIPTION
**Pull request by dev-madhurendra**
[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### Checklist:

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new JavaScript files are placed inside an existing directory.
- [x] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [x] All new algorithms have a URL in their comments that points to Wikipedia or another similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by appgurueu — CHANGES_REQUESTED** [review]
1. Get rid of the changes to `package.json` or `package-lock.json`.
2. This is not a general solution as the name currently suggests. It only works if (1) there is exactly one unique element (2) all duplicate elements occur an even number of times.
3. This can be written more concisely as `arr.reduce((acc, val) => acc ^ val, 0)`.

**Review by appgurueu — COMMENTED** [review]
* Please use a proper JSDoc comment (and don't phrase it as "if the interviewer asks" etc.; that's fluff that should be omitted).
* By "get rid of the changes to `package.json` and `package-lock.json`" I meant remove the changes to them from this PR, not remove the files.

**Review by appgurueu — COMMENTED** [review]
Please use proper [JSDoc](https://jsdoc.app/) comments.

**Comment by dev-madhurendra** [comment]
> Please use proper [JSDoc](https://jsdoc.app/) comments.

>> Which is not a proper comment

**Review by appgurueu — APPROVED** [review]

**Review by raklaptudirm — APPROVED** [review]

**Pull request merged**
