### PR TITLE
Sliding window

### PR DESCRIPTION
**Pull request by Aditya1942**
# Welcome to JavaScript community

[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new JavaScript files are placed inside an existing directory.
* [x] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by Aditya1942** [comment]
i have add 2 new solutions to a problem with different complexity.
all guide lines are followed

**Comment by raklaptudirm** [comment]
Please move the folder into the `Dynamic-Programming/` directory.

**Review by Aditya1942 — COMMENTED** [review]
2 new solutions added

**Comment by raklaptudirm** [comment]
I asked you to move the `Sliding-window` directory into the `Dynamic-Programming` directory.

**Comment by Aditya1942** [comment]
should i move sliding-window folder in dynamic-programming?

**Comment by raklaptudirm** [comment]
Yes.

**Comment by Aditya1942** [comment]
> Yes.
is it ok ? i mean sliding-window dosen't use Dynamic-Programming concept
i suggest make a separate folder for that

**Comment by raklaptudirm** [comment]
Sliding window IS a part of dynamic programming, so it should be inside that folder. Also, sliding window is not a broad category of algorithms, it is a category of dynamic programming.

**Comment by Aditya1942** [comment]
> Sliding window IS a part of dynamic programming, so it should be inside that folder. Also, sliding window is not a broad category of algorithms, it is a category of dynamic programming.

ok

**Comment by Aditya1942** [comment]
done.
anything else?

**Comment by Aditya1942** [comment]
@raklaptudirm
 hey can we now merge this

**Review by raklaptudirm — APPROVED** [review]

**Pull request merged**
