### PR TITLE
FindLCM: Improve code readablility

### PR DESCRIPTION
**Pull request by CarlosZoft**
# Welcome to the JavaScript community

[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

- [x] Fix a bug or typo in an existing algorithm?
- [x] Documentation change?

### Checklist:

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.

### CODE REVIEW

**Review by appgurueu — CHANGES_REQUESTED** [review]
I like the return; there already is a similar PR (https://github.com/TheAlgorithms/Javascript/pull/951/files) concerning the `Math.max` instead of the if-else. Again, please revert the change that relies on JS truthiness and use explicit comparison against zero (`=== 0`) as it is more readable and less error-prone in general.

(Technically the condition could even be shortened further as `!((lcm % num1) || (lcm % num2))` according to De Morgan's law, but that sure would be unreadable ;) )

**Comment by CarlosZoft** [comment]
true, i will fix this

**Comment by CarlosZoft** [comment]
Fixed it. But what you think, i remove math.max approached in another PR or not?

**Review by appgurueu — APPROVED** [review]
Looks fine now. LGTM.

**Review by raklaptudirm — APPROVED** [review]

**Pull request merged**
