### PR TITLE
Update BinarySearch.js

### PR DESCRIPTION
**Pull request by bigal2331**
Simplifying the calculation for midpoint.

low + Math.floor((high - low)/2) === Math.floor((high + low)/2)

# Welcome to JavaScript community

[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new JavaScript files are placed inside an existing directory.
* [ ] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by raklaptudirm — COMMENTED** [review]
This does not change the calculation time too much, but it does make the program harder to decipher. Remember, this repository is primarily aimed at beginners, so sometimes, simplicity is better than efficiency. 

The change in calculation time is almost negligible, given that addition and subtraction between floating points is an extremely fast operation. On the other hand, there is a huge loss of self explanation in the code. So I think this change is not worth putting into the code. Let me know if you have different opinions.

**Comment by CarlosZoft** [comment]
I agree with @bigal2331, but not because it's apparently faster/cheaper. but because there is almost a redundancy in the current solution.

**Comment by raklaptudirm** [comment]
@CarlosZoft redundancy?

**Comment by raklaptudirm** [comment]
I am for the time being closing this pr, but feel free to point out how it can improve the repository, and I will be happy to reopen it.

**Pull request closed without merging**
