### PR TITLE
Added Rectangle.js and Rectangle.test.js to "Geometry" and it's "test" Directories 

### PR DESCRIPTION
**Pull request by debnath003**
[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### Checklist:

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new JavaScript files are placed inside an existing directory.
- [x] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [x] All new algorithms have a URL in their comments that points to Wikipedia or another similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by debnath003** [comment]
@appgurueu @raklaptudirm please approve this PR and merge this so that it can be eligible for hacktoberfest

**Comment by debnath003** [comment]
@appgurueu @raklaptudirm please check my PR #1413 and approve for hacktoberfest

**Comment by debnath003** [comment]
Can I update the comment? @appgurueu

**Comment by appgurueu** [comment]
> Can I update the comment? @appgurueu

This is not about a comment, this is about the contents of this PR (adding a trivial rectangle class with area / perimeter functions) which I don't see adding much value. To quote the contribution guidelines:

> [...] each algorithm in this repo should add a unique value

(note: we'll try to make it more clear in the future what our expectations are, and that we mostly aren't interested in trivial algorithms; if in doubt, open an issue before working on an implementation)

**Pull request closed without merging**
