### PR TITLE
feat: remove `twinPrime`

### PR DESCRIPTION
**Pull request by vil02**
[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

This PR removes the function `twinPrime` as suggested in: https://github.com/TheAlgorithms/JavaScript/pull/1641#issuecomment-1986858870

~~This PR adds a test covering this line:~~ https://github.com/TheAlgorithms/JavaScript/blob/4a4ed57d4285fc61b5385d2c2525369ce2c4e6fb/Maths/TwinPrime.js#L23
~~And reorganizes existing tests.~~

### Checklist:

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new JavaScript files are placed inside an existing directory.
- [x] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [x] All new algorithms have a URL in their comments that points to Wikipedia or another similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by appgurueu — COMMENTED** [review]
This improves coverage of the existing implementation, but I think the existing implementation has a bug: According to Wikipedia

> A twin prime is a prime number that is either 2 less or 2 more than another prime number

So the (a) twin prime of `7` should be `5`.

**Comment by vil02** [comment]
> This improves coverage of the existing implementation, but I think the existing implementation has a bug: According to Wikipedia
> 
> > A twin prime is a prime number that is either 2 less or 2 more than another prime number
> 
> So the (a) twin prime of `7` should be `5`.

What should then be the `twinPrime(5)`?

I have to admit that I did not get this function is supposed to do. It would be more natural to have a function like `isTwinPrime`.

**Comment by appgurueu** [comment]
> What should then be the `twinPrime(5)`?

I think either 3 or 7 would be fine.

We may also remove this function entirely, or replace it with an "is twin prime" variant as you suggest, IMO. It's just confusing (and trivial) as is.

**Comment by vil02** [comment]
> > What should then be the `twinPrime(5)`?
> 
> I think either 3 or 7 would be fine.
> 
> We may also remove this function entirely, or replace it with an "is twin prime" variant as you suggest, IMO. It's just confusing (and trivial) as is.

I will remove it.

**Review by appgurueu — APPROVED** [review]

**Review by raklaptudirm — APPROVED** [review]

**Pull request merged**
