### PR TITLE
added URLShortener method in the string category

### PR DESCRIPTION
**Pull request by suryapratapsinghsuryavanshi**
# Welcome to JavaScript community

[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new JavaScript files are placed inside an existing directory.
* [x] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by raklaptudirm** [comment]
Algorithms are generalized solutions, not solutions to a specific problem. I would like you to remove the context of url shortening and make the algorithm to be just a number to unique string converter.

**Comment by suryapratapsinghsuryavanshi** [comment]
I think this is a new something because most of the algorithm maximum change base36, so we use upper case letter in it so they make some difference of other algorithms.

**Comment by raklaptudirm** [comment]
Then again, the base number can be anything. If I merge this PR, I also have to merge any PR implementing conversion to any arbitrary base. Therefore, I do not think I should merge this PR. I will, of course, get the other members opinions before that, but that is still what I believe.

Conversions to base 2(binary) and base 16(hexadecimal) are acceptable because these are used so frequently that their algorithms have become sort of unique. That does not imply that an algorithm implementing base 101 or other is a new algorithm

**Comment by trasherdk** [comment]
On a side note. Any email containing a URL shortened link will be tagged as high scoring spam and silently discarded (on my servers).

**Comment by raklaptudirm** [comment]
I do not think thats relevant here @trasherdk

**Pull request closed without merging**
