### PR TITLE
Removed array Insertion and added numbers Fixes: #1341

### PR DESCRIPTION
**Pull request by ROHAN13498**
[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

Fixes: #1341  
### Describe your change:

- [ ] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [x] Documentation change?

### Checklist:

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new JavaScript files are placed inside an existing directory.
- [x] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [x] All new algorithms have a URL in their comments that points to Wikipedia or another similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by appgurueu — APPROVED** [review]
That comment should probably be removed or turned into a test case. Either way this change is an improvement already though.

**Review by CarlosZoft — APPROVED** [review]

**Comment by raklaptudirm** [comment]
@ROHAN13498 are you interested in implementing the test cases? Cause I see no point in improving upon something that is explicitly disallowed by the contribution guidelines.

**Comment by ROHAN13498** [comment]
Done. I will work on it.

**Comment by ROHAN13498** [comment]
> @ROHAN13498 are you interested in implementing the test cases? Cause I see no point in improving upon something that is explicitly disallowed by the contribution guidelines.


Hey,There is no testcases file for maxheap should I create a newfile and work on it?

image

**Comment by raklaptudirm** [comment]
> > @ROHAN13498 are you interested in implementing the test cases? Cause I see no point in improving upon something that is explicitly disallowed by the contribution guidelines.
> 
> Hey,There is no testcases file for maxheap should I create a newfile and work on it?
> 
> image

Yes you should.

**Comment by appgurueu** [comment]
The current situation is a bit awkward; we have a max heap, a min heap, and a priority queue, all of which are more or less based on similar code. This should ideally be deduplicated; max and min heap can effectively use the same code with a different comparison function, and a priority queue should just add an index from element to position in heap on top of that.

**Comment by ROHAN13498** [comment]
> The current situation is a bit awkward; we have a max heap, a min heap, and a priority queue, all of which are more or less based on similar code. This should ideally be deduplicated; max and min heap can effectively use the same code with a different comparison function, and a priority queue should just add an index from element to position in heap on top of that.

So you are suggesting that Instead of having separate implementations for Max Heap and Min Heap, it's better to create a single generic heap data structure that can handle both max and min heaps by using a comparison function to determine the order of elements.

Should I work on implementing this  single heap data structure or write tests for max heap?

**Comment by appgurueu** [comment]
> > The current situation is a bit awkward; we have a max heap, a min heap, and a priority queue, all of which are more or less based on similar code. This should ideally be deduplicated; max and min heap can effectively use the same code with a different comparison function, and a priority queue should just add an index from element to position in heap on top of that.
> 
> So you are suggesting that Instead of having separate implementations for Max Heap and Min Heap, it's better to create a single generic heap data structure that can handle both max and min heaps by using a comparison function to determine the order of elements.

Yes.

> Should I work on implementing this single heap data structure or write tests for max heap?

The former; the latter would pretty much be manual test duplication, which seems pretty unnecessary to me.

**Comment by ROHAN13498** [comment]
> > So you are suggesting that Instead of having separate implementations for Max Heap and Min Heap, it's better to create a single generic heap data structure that can handle both max and min heaps by using a comparison function to determine the order of elements.
> 
> Yes (though my suggestion goes even further: we could deduplicate some heap and priority queue code by making the priority queue extend or use the heap, but you don't need to do this because it is trickier).
> 
> > Should I work on implementing this single heap data structure or write tests for max heap?
> 
> The former; the latter would pretty much be manual test duplication, which seems pretty unnecessary to me.

I'll start by working on test cases file for maxheap data structure  for now . Once that's in place, I'll try to tackle code deduplication.

**Comment by appgurueu** [comment]
> I'll start by working on test cases file for maxheap data structure for now . Once that's in place, I'll try to tackle code deduplication.

As said, I don't think that's a good idea. You will be duplicating min heap tests effectively.

**Comment by ROHAN13498** [comment]
Hey @appgurueu  I have deduplicated the codes of min heap and maxheap into single binaryheap class should I create a issue for it and create a PR or should I do PR directly.

**Pull request closed without merging**
