### PR TITLE
fixed the merge implementation in MergeSort

### PR DESCRIPTION
**Pull request by guyariely**
# Welcome to JavaScript community

[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### **Describe your change:**

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new JavaScript files are placed inside an existing directory.
* [x] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by guyariely** [comment]
This is an update on TheAlgorithms/Javascript#579.

**Comment by pomkarnath98** [comment]
Thanks for your contribution @guyariely.
But even after #579, you didn't rectify your mistakes. Once again mentioning, try to use `let` and `const` instead of using `var` and commit.
Otherwise, the code is working fine.

**Comment by guyariely** [comment]
@pomkarnath98 there are no `var` in my commit ... it only includes `let` and `const`.

**Comment by pomkarnath98** [comment]
It's not in your commit but in your file.

image

**Comment by guyariely** [comment]
I updated the rest of the file to only include `let` / `const`.

**Pull request merged**
