### PR TITLE
Adding an algorithm AlphaNumericPalindrome from freecodecamp

### PR DESCRIPTION
**Pull request by SyedFasiuddin**
# Welcome to JavaScript community

[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new JavaScript files are placed inside an existing directory.
* [x] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by raklaptudirm** [comment]
@cclauss Would you consider this as a proper algorithm?

**Comment by cclauss** [comment]
I don’t do JavaScript so I cannot comment on efficiency but I would have written this as `return isPalandrome(s) and isAlphaNumeric(s)`.  In Python, each of those functions would be one-liners.

It does however seem to fit the definition of an algorithm unless I am missing something.

**Comment by SyedFasiuddin** [comment]
> 
> 
> I don’t do JavaScript so I cannot comment on efficiency but I would have written this as `return isPalandrome(s) and isAlphaNumeric(s)`. In Python, each of those functions would be one-liners.
> 
> It does however seem to fit the definition of an algorithm unless I am missing something.

Yes this can be done in two line in JS as well but, this repository being beginner friendly, I wanted to make it as simple as possible, and if you not include the comments and empty lines this function only takes 8 lines

**Comment by SyedFasiuddin** [comment]
This error that is popping up saying "unnecessary escape character" in file "Javascript\String\test\AlphaNumericPalindrome.test.js" at lines 8 and 12 is actually inside a string and is a test case requirement, so I don't think this error is any significant in this case.

**Comment by cclauss** [comment]
```python
import string


def is_alphanumeric_palendrome(s: str) -> bool:
    """
    To test, run: `python3 -m doctest v alphanumeric_palendrome.py`
    >>> is_alphanumeric_palendrome("eye")
    True
    >>> is_alphanumeric_palendrome("0_0 (: /-\ :) 0-0")
    True
    >>> is_alphanumeric_palendrome("five|\_/|four")
    False
    >>> is_alphanumeric_palendrome("A man, a plan, a canal. Panama")
    True
    >>> is_alphanumeric_palendrome(" eye for of 1 eye.")
    False
    """
    alphanumeric = string.ascii_letters + string.digits
    s = "".join(char for char in s if char in alphanumeric).lower()
    return s == "".join(reversed(s))
```

**Comment by cclauss** [comment]
> this can be done in two line in JS

For my edification, can you please show me here?

**Comment by SyedFasiuddin** [comment]
> For my edification, can you please show me here?

```javascript
const alphaNumericPlaindrome = (str) => {
    const string = str.replace(/[^a-zA-Z0-9]*/g, '').toLowerCase()
    return string === string.split('').reverse().join('')
}
```

Here you go, this will work exactly as your python code but there is nothing like doctest in js so..

**Comment by cclauss** [comment]
https://github.com/davidchambers/doctest

**Pull request merged**
