### PR TITLE
Add max word algorithm

### PR DESCRIPTION
**Pull request by farha1**
# Welcome to JavaScript community

[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new JavaScript files are placed inside an existing directory.
* [x] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by farha1** [comment]
hi @pomkarnath98 , can you add this pull request as part of hacktoberfest ?

this is my first contribution in Hacktoberfest 2021.. thanks..

**Comment by raklaptudirm** [comment]
@pomkarnath98 please wait for my review too before merging.

**Comment by raklaptudirm** [comment]
@farha1 Merging a pull request into a hacktoberfest repository automatically marks it as a hacktoberfest contribution.

**Comment by farha1** [comment]
> @farha1 Merging a pull request into a hacktoberfest repository automatically marks it as a hacktoberfest contribution.
O I see..

but why in my hacktoberfest profile still 0 contribution.. do you know? @raklaptudirm

**Comment by pomkarnath98** [comment]
@raklaptudirm Did I miss anything in this PR?

**Comment by farha1** [comment]
apparently I forgot to connect my github account.. only gitlab account.. hmmm..

**Comment by raklaptudirm** [comment]
@pomkarnath98 No but you could have.

**Comment by pomkarnath98** [comment]
> @pomkarnath98 No but you could have.

Don't worry @raklaptudirm. I have been reviewing and merging PR for the last 12 months :)

**Comment by raklaptudirm** [comment]
Still, its better to have more opinions.

**Comment by pomkarnath98** [comment]
okay then, let's follow this

**Pull request merged**
