### PR TITLE
Add FindSecondLargestSort

### PR DESCRIPTION
**Pull request by MatthewPalmer9**
# Welcome to JavaScript community

### **Describe your change:**

* [ x ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [ x ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [ x ] This pull request is all my own work -- I have not plagiarized.
* [ x ] I know that pull requests will not be merged if they fail the automated tests.
* [ x ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ x ] All new JavaScript files are placed inside an existing directory.
* [ x ] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [ x ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ x ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by marsonya — COMMENTED** [review]
This doesn't really look like an algorithm.
The second largest number can be derived using any of the sort algorithm and simply accessing the second index.

@pomkarnath98, @itsvinayak, @ruppysuppy what do you guys think?

**Comment by MatthewPalmer9** [comment]
@marsonya The issue with accessing the second number is when you get an array such as:

[1, 2, 4, 6, 7, 8, 10, 10]

The second largest is 8, but choosing the second to last index would return 10. This algorithm filters for unique values. It bypasses the case of repeating numbers.

**Comment by ruppysuppy** [comment]
> This doesn't really look like an algorithm.

I too feel the same. Let's hear what others think

**Review by itsvinayak — COMMENTED** [review]
https://www.geeksforgeeks.org/find-second-largest-element-array/

**Review by ruppysuppy — APPROVED** [review]
I believe that

**Review by marsonya — APPROVED** [review]

**Pull request merged**
