### PR TITLE
Improving the coding standard for AvLTree Data Structure

### PR DESCRIPTION
**Pull request by rraj798**
# Welcome to JavaScript community

[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new JavaScript files are placed inside an existing directory.
* [x] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by raklaptudirm — CHANGES_REQUESTED** [review]
Please create a `/test` sub-directory and write some `jest` tests for the algorithm there. I know they were not there, but they will further enhance the code quality and help catch bugs.

**Comment by rraj798** [comment]
> Please create a `/test` sub-directory and write some `jest` tests for the algorithm there. I know they were not there, but they will further enhance the code quality and help catch bugs.

The test cases are created

**Review by raklaptudirm — CHANGES_REQUESTED** [review]
The tests are failing, so please check the error and fix them.

**Comment by rraj798** [comment]
> The tests are failing, so please check the error and fix them.

Test cases are working properly in local without any issues

**Comment by raklaptudirm** [comment]
Please check if you have any local changes which you have not yet committed.

**Review by raklaptudirm — CHANGES_REQUESTED** [review]
Please format your code with `standard.js`.

**Review by raklaptudirm — APPROVED** [review]

**Pull request merged**
