### PR TITLE
Update MinimumCostPath.js

### PR DESCRIPTION
**Pull request by DhruvGheewala**
# Welcome to JavaScript community

### **Describe your change:**

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new JavaScript files are placed inside an existing directory.
* [x] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by pomkarnath98** [comment]
Thanks for your contribution. But your code isn't giving correct output. Please re-check it

**Comment by DhruvGheewala** [comment]
Hey @pomkarnath98, can you please that test case on which code fails??

**Comment by pomkarnath98** [comment]
@DhruvGheewala what should be the output for your testcase and what is coming here?

**Comment by DhruvGheewala** [comment]
> @DhruvGheewala what should be the output for your testcase and what is coming here?

Sorry, I don't understand what are you trying to say...

**Comment by pomkarnath98** [comment]
IMG_20201220_181214
Can you please tell what should be the output for this and what is your code giving?

**Comment by DhruvGheewala** [comment]
@pomkarnath98 , I have resolved and updated the file. You can see it [here](https://github.com/TheAlgorithms/Javascript/pull/551).

**Pull request closed without merging**
