### PR TITLE
Number of Subset equal to given sum

### PR DESCRIPTION
**Pull request by rverma13927**
# Welcome to JavaScript community

### **Describe your change:**

* [x] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new JavaScript files are placed inside an existing directory.
* [x] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by itsvinayak** [comment]
@rverma13927 please fill check box
and follow npx standard --fix
read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md)

**Comment by itsvinayak** [comment]
use let in place of var 
and don't put ';' and end

**Comment by itsvinayak** [comment]
change file name also

**Comment by itsvinayak** [comment]
@rverma13927  same algorithm already exit "Javascript/Dynamic-Programming/KadaneAlgo.js "

**Comment by rverma13927** [comment]
Please tell me it meets your requirement or not.

**Comment by itsvinayak** [comment]
@rverma13927  thanks for  contributing

**Pull request merged**
