### PR TITLE
Combined Min Heap and Max Heap classes

### PR DESCRIPTION
**Pull request by ROHAN13498**
[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

Deduplicated the code of Minheap and Maxheap and used a single binary heap class.
### Describe your change:

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### Checklist:

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new JavaScript files are placed inside an existing directory.
- [x] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**UserProfile.js is allowed but userprofile.js,Userprofile.js,user-Profile.js,userProfile.js are not
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or another similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains Fixes: #{$ISSUE_NO}.

### CODE REVIEW

**Review by appgurueu — CHANGES_REQUESTED** [review]
Looks mostly fine. Some points:

* The tests are pretty much duplicated. IMO it would be fine to test just min or max heap, then test that the comparator is being used at all with a small example of the opposite ordering. But I'm not terribly opposed to this; it needs to be tested one way or another.
* You got rid of explanatory comments. Please readd some. At the very least, please add JSDoc comments to public methods, and mark "private" methods (like `bubbleUp`, `sinkDown` and `swap`) as such using the `#` prefix.

**Comment by ROHAN13498** [comment]
Yeah!You are right.I will work on that and get back to you.

**Comment by ROHAN13498** [comment]
> * You got rid of explanatory comments. Please readd some. At the very least, please add JSDoc comments to public methods, and mark "private" methods (like `bubbleUp`, `sinkDown` and `swap`) as such using the `#` prefix.

Should I install jsdoc node module or just write the comments and leave them like that.

**Comment by ROHAN13498** [comment]
> > * You got rid of explanatory comments. Please readd some. At the very least, please add JSDoc comments to public methods, and mark "private" methods (like `bubbleUp`, `sinkDown` and `swap`) as such using the `#` prefix.
> 
> Should I install jsdoc node module or just write the comments and leave them like that.

**Review by appgurueu — COMMENTED** [review]
As said, bubbleUp / sinkDown / swap should all be private (not just documented as private, but actually private by prefixing them with `#`).

**Review by appgurueu — APPROVED** [review]
Though you have some redundant tags there (e.g. there's no need for `@private` for `#method`s, no need to document the `heap` member (which btw should maybe also be private)).

**Comment by ROHAN13498** [comment]
I did this under hactober fest will it be counted?

**Comment by appgurueu** [comment]
> I did this under hactober fest will it be counted?

Yes, it should be. From the Hacktoberfest website:

> Maintainers accept PR/MRs by merging them, labeling them “hacktoberfest-accepted,” **or giving them an overall approving review**.

The last point is what I effectively just did :)

**Comment by ROHAN13498** [comment]
> The last point is what I effectively just did :)

Thanks a lot @appgurueu

**Comment by appgurueu** [comment]
> > The last point is what I effectively just did :)
> 
> Thanks a lot @appgurueu

np, thank you for your contribution :) it's important that every now and then someone takes the time to refactor something

**Review by raklaptudirm — APPROVED** [review]

**Comment by ROHAN13498** [comment]
@appgurueu are there any more issues that you would suggest to work on?

**Comment by appgurueu** [comment]
> @appgurueu are there any more issues that you would suggest me to work on?

No, but if you see other places where code is duplicated, or want to add an interesting algorithm, feel free to open a PR :)

**Pull request merged**
