### PR TITLE
Algorithm to calculate the Arithmetic Geometric Mean

### PR DESCRIPTION
**Pull request by Rudxain**
Added an algorithm to compute/find the Arithmetic-Geometric Mean between 2 numbers `a` and `g`. I thought it would be a good idea since it shows how to compute at full precision without an `epsilon` comparison, and there's already an Arithmetic Mean so I added this for completeness.

# Welcome to JavaScript community

[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new JavaScript files are placed inside an existing directory.
* [x] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by raklaptudirm — CHANGES_REQUESTED** [review]
Please add tests for the algorithm.

**Comment by Rudxain** [comment]
> Please add tests for the algorithm.

I added the test script now, but the "build" stage says that none of the methods are functions. "`toBe` is not a function", and "`toEqual` is not a function". Is this normal?

**Review by raklaptudirm — CHANGES_REQUESTED** [review]
`toBe` should be outside `expect`. Please fix all the instances where you put it inside.

**Comment by Rudxain** [comment]
My bad, sorry. I didn't notice. I'll fix it now

**Comment by Rudxain** [comment]
I'll fix the other bugs now

**Review by raklaptudirm — APPROVED** [review]

**Pull request merged**
