### PR TITLE
Find max recursion

### PR DESCRIPTION
**Pull request by Exortions**
[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### Describe your change:

- [x] Add an algorithm

### Checklist:

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new JavaScript files are placed inside an existing directory.
- [x] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by appgurueu — DISMISSED** [review]
You seem to have kinda duplicated my explanatory comments regarding the left shift. Also note that you don't have to open a new PR each time. Nevertheless, this is mergeable.

**Comment by Exortions** [comment]
> You seem to have kinda duplicated my explanatory comments regarding the left shift. Also note that you don't have to open a new PR each time. Nevertheless, this is mergeable.

Yeah, I don't know how to add commits to a PR.

**Review by appgurueu — DISMISSED** [review]
Fixed.

**Comment by Exortions** [comment]
Thanks for the changes, I know now how to add commits to a PR :)

**Review by raklaptudirm — APPROVED** [review]

**Pull request merged**
