### PR TITLE
Add proper test to Backtracking/Sudoku

### PR DESCRIPTION
**Pull request by defaude**
### **Describe your change:**

Refactored the test for the Backtracking/Sudoku algorithm out into a proper jest test file.

### **Checklist:**

* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new JavaScript files are placed inside an existing directory.
* [x] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by pomkarnath98** [comment]
If the algorithm is working fine, then no need to modify it. Someone from the team has already approved and merged by reviewing it.
Moreover, don't create test cases for other's files. Try to create PR with a new Algorithm problem.

**Comment by defaude** [comment]
Hi @pomkarnath98! I did not _change_ the original implementation. I only removed the test / driver code from the implementation file and replaced it with a proper (more in-depth) test case.

Why would you dis-encourage people to contribute to already-existing implementations? :( The contribution doc explicitly encourages that.

**Comment by raklaptudirm** [comment]
@pomkarnath98 The repositories of TheAlgorithms are for educational purposes. Here are the reasons why tests are useful even for perfectly coded algorithms:
1. Tests show the learner how to use a particular algorithm.
2. It shows where the algorithm can and should fail.
3. It makes it easier for the maintainers to make sure changes to an algorithm do not break it.

**Comment by raklaptudirm** [comment]
@defaude Please format your code with [`standard.js`](https://standardjs.com/).

**Comment by pomkarnath98** [comment]
@defaude I'm really thankful that people like you are getting time to contribute to open sources. 
Please, don't take my words in the wrong way. But if you can find any improvement anywhere, you could've raised an issue and then resolved the issue by making this PR.
Your description itself was `Refactored..` so that I got confused there.
Anyway, format your code. We'll review and merge :)

Your points are welcome @raklaptudirm.

**Pull request merged**
