### PR TITLE
Added test script for CreatePermuation string algorithm and file name change

### PR DESCRIPTION
**Pull request by thivagar-manickam**
# Welcome to JavaScript community

[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### **Describe your change:**

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new JavaScript files are placed inside an existing directory.
* [ ] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by ruppysuppy — CHANGES_REQUESTED** [review]
Use `standard` to format the code

**Comment by thivagar-manickam** [comment]
> 
> 
> Use `standard` to format the code

I have fixed the formatting issues by using standard, but still, the job fails. Can you help me figure out what is the issue now?

**Comment by ruppysuppy** [comment]
I believe its due to `String/LevenshteinDistance.test.js` file. Pull the changes from master (`git pull <upstream> master`) then push it again (`git push <origin> <branch-name>`)

**Comment by thivagar-manickam** [comment]
Will create a new PR

**Pull request closed without merging**
