### PR TITLE
Quality-of-Life: Ignore intelliJ workspace folder

### PR DESCRIPTION
**Pull request by defaude**
### **Describe your change:**

Simple quality-of-life fix: Ignore intelliJ's workspace folder. intelliJ is my daily driver for working with code. Everytime I clone a repo and open up its contents in intelliJ, the IDE will automatically create the `.idea` folder for storing project-specific settings etc.

### **Checklist:**

* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.

### **Not applicable items from the checklist (since I only changed the .gitignore file):**

* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new JavaScript files are placed inside an existing directory.
* [ ] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by trasherdk** [comment]
@defaude You might want to check out [Global gitignore](https://gist.github.com/subfuzion/db7f57fff2fb6998a16c) for a solution.

**Comment by defaude** [comment]
Thanks for the suggestion! I do know about this - but many people don't ;) So I _kind of_ disagree with adding this to an open source repo's gitignore being a "poor practice".

**Comment by pomkarnath98** [comment]
This is not a valid PR @defaude. Please raise a PR with a valid Algorithm.

**Comment by defaude** [comment]
Thanks for looking into this one! However, I humbly disagree with the "is not a valid PR" part. The contribution doc explicitly encourages "any" contribution aside from only adding new algorithms. So in my understanding, quality-of-life improvements are just as valid. I especially marked the PR as such :)

I was about to add a few more changes later. But to get started, I wanted to improve the QoL especially for newcomers to this repo.

And yeah, I know, one can discuss the whole "should we include editor / OS-specific stuff in .gitignore" topic - and I'll gladly chime in :) Just seeing that `.DS_Store` was already in the .gitignore I figured it's okay to add a tiny improvement here.

**Comment by pomkarnath98** [comment]
Thank you for sharing the content. You have already some open PR.
Please add this one line of code there and write the proper commit message.

**Comment by defaude** [comment]
I'd rather not mix concerns from two distinct PRs. Why not just re-open this change here?

**Comment by pomkarnath98** [comment]
Well, I've added it in .gitignore
Thanks :)

**Pull request closed without merging**
