### PR TITLE
add `Index` in `DIRECTORY.md`

### PR DESCRIPTION
**Pull request by BhumikaSaini**
# Welcome to JavaScript community

[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### **Describe your change:**

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

What's changed?

| File | Change | Comments |
| - | - | - |
| `DIRECTORY.md` | Added an `Index` | Helps quickly jump to a section |
| `DIRECTORY.md` | Added `Back to top` links | Helps quickly jump back to top from a section |
| `DIRECTORY.md` | Converted unordered lists to ordered lists | Helps quickly view the 'number' of algorithms in a section and easier referencing |

Why do this?
As we can already see, few sections are growing fast. The file will inevitably become more difficult to reference without proper navigation links.

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new JavaScript files are placed inside an existing directory.
* [x] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by BhumikaSaini** [comment]
Hi @raklaptudirm,
Sorry, I didn't know it was auto-generated. I believe the file to modify is [UpdateDirectory.mjs](https://github.com/TheAlgorithms/Javascript/blob/master/.github/workflows/UpdateDirectory.mjs) then. However, is this change something we want to incorporate? I would proceed only if we want to do this.
Thanks!

**Comment by cclauss** [comment]
The problem with making this change is that adding a new algorithm will add that line and then modify all the lines after it to add 1 to their index.  This makes the diff big which gives maintainers more work to do when reviewing each pull request.

**Comment by raklaptudirm** [comment]
@BhumikaSaini If you have a different opinion, please let us know.

**Comment by BhumikaSaini** [comment]
No @raklaptudirm, I agree. The concern raised by cclauss is very valid. It is better if we don't proceed with this.
Thank you!

**Pull request closed without merging**
