### PR TITLE
Pow function optimization using exponentiation by squaring

### PR DESCRIPTION
**Pull request by farha1**
# Welcome to JavaScript community

[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### **Describe your change:**

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new JavaScript files are placed inside an existing directory.
* [x] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by tjgurwara99 — COMMENTED** [review]
Isn't this slower? This is using a recursive approach - arguably slower than the iterative one. You should add a separate function instead of overwriting the already fast implementation. If you still think this is fast, could you write a benchmark to see the differences.

Also, note that I'm not against having your approach - in fact, your approach is more mathematical but I question that the title of this PR is suitable for what you're trying to do here.

**Comment by booleans-oss** [comment]
I've decided to try and benchmark this new implementation. The screenshots provided are only tested with the number 5, 10, 20 and 50. And the exponents go from 0 to 100. Larger variables could be used but I noticed that the pattern stay approximately the same so I decided to stay in that range.

<details>
<summary>Screenshots</summary>

time-5

time-10

time-20

time-50

</details>

In my opinion, the difference in execution between the two implementations is too small to categorically say that one is faster than the other. We can clearly see some peaks but not significantly enough to choose between the two.

We also should keep in mind that the code that I used to measure the elapsed time might not be perfect. There might be a lot more variables affecting the execution time. (If needed, I can provide the benchmarking code I made).  

I hope it helps.

**Comment by booleans-oss** [comment]
I made a simple benchmarking workspace to see the execution time difference for the two implementations. For simplicity sake, I use any integers from 0 to 100 and exponents range from 0 to 10000. 

<details>
<summary>Screenshots</summary>

time-10

time-100

time-1000

time-10000

</details>

The screenshots show the same results as the previous benchmarks: **the previous implementation is slower than the new one**.

**Comment by raklaptudirm** [comment]
The benchmarks are good, but I would still suggest to keep both implementations.

**Review by tjgurwara99 — CHANGES_REQUESTED** [review]
It's good that you improved this, however my previous comment was just suggesting that you shouldn't remove the previous implementation. I still think you should NOT REMOVE the old implementation but rather create a separate function, calling `powIterative` and `powRecursive` or something along those lines.

**Comment by raklaptudirm** [comment]
@farha1 seems like you abandoned this pr. Please go through with the review comments if you still want to work on this.

**Comment by appgurueu** [comment]
> Isn't this slower? This is using a recursive approach - arguably slower than the iterative one. You should add a separate function instead of overwriting the already fast implementation. If you still think this is fast, could you write a benchmark to see the differences.

No, this implementation is way faster in fact. The naive algorithm does O(n) multiplications where n is the exponent. This algorithm halves the exponent in each step. The recursive call tree thus has logarithmic depth. Yet the effort per call is constant. So this is O(log n), way faster.

In practice the iterative approach might be faster for reasonably small exponents.

I too suggest keeping both, but this is generally the preferable approach.

Suggestion to make it faster: You don't need to check for all edge cases (0, 1, negative exponents) if you check for a couple in the calling func already and then call a recursive helper which only receives the exponents you expect.

**Review by appgurueu — APPROVED** [review]

**Comment by raklaptudirm** [comment]
@farha1 You need to fix the branch conflicts.

**Comment by tjgurwara99** [comment]
> No, this implementation is way faster in fact. The naive algorithm does O(n) multiplications where n is the exponent. This algorithm halves the exponent in each step.

Yeah, didn't notice the halving of the exponent😅

Though still think instead of overwriting the function, we should keep both.

**Comment by raklaptudirm** [comment]
@farha1 seems to have abandoned this pr.

**Pull request closed without merging**
