### PR TITLE
Algorithm to print a month's calendar.

### PR DESCRIPTION
**Pull request by raklaptudirm**
This pull request adds an algorithm to `Dynamic-programming` which accepts a month in the format m/y, and prints the month's calendar.

Commits before 0f703a5 are unrelated and have been reverted back in 7c3b0ad.

# Welcome to JavaScript community

[Open in Gitpod](https://gitpod.io/from-referrer/)&nbsp;[know more](https://www.gitpod.io/docs/pull-requests/)

### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new JavaScript files are placed inside an existing directory.
* [x] All filenames should use the UpperCamelCase (PascalCase) style.  There should be no spaces in filenames.
     **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by raklaptudirm** [comment]
#14 Contribution. Added a new algorithm.

**Review by ruppysuppy — CHANGES_REQUESTED** [review]
Split the one liner conditionals into different lines. In `isLeapYear` _else_ is not required, you can just use _return false_

**Comment by raklaptudirm** [comment]
> Split the one liner conditionals into different lines. In `isLeapYear` _else_ is not required, you can just use _return false_

Removed the else but breaking the conditional raises standard js formatting issues.

**Comment by ruppysuppy** [comment]
@raklaptudirm from next time please open separate PRs for different tasks (you had squashed Kadane's algorithm improvement and the calendar together)

**Comment by raklaptudirm** [comment]
> @raklaptudirm from next time please open separate PRs for different tasks (you had squashed Kadane's algorithm improvement and the calendar together)

Actually, I ran `standard --fix` on the code so it automatically changed that.

**Pull request merged**
