### PR TITLE
Changes for consolidation

### LINKED ISSUE #720: Consolidating some things
Hey everyone! I just arrived here at this repo and would love to contribute a bit :)

Looking at the code organisation and the test setup, it's rather confusing for newcomers right now. Should we discuss those cross-cutting things a bit and then decide the direction going forward? Here's a few ideas - feedback very much welcome:

**Code structure**: Maybe we could define a "template" for code/algorithm files that new code should follow and/or existing code could be migrated towards. Some things to keep in mind, though:
- Implementation files (modules?) should adhere to a common structure (e.g. ESM)
- Implementation code should be stateless (i.e. it should be possible to call the implementation multiple times without side effects between test runs)
- Algorithm implementation should refrain from outputting to the console
- ... (ideas welcome)

**Test setup**: There should be just _one_ solution for testing. Do we want to use doctest going forward? Or do we want to use Jest? But keeping both is a source of confusion and will eventually lead to degrading code quality / clarity. (This is basically the attempt to revive the discussion in #142 even though I'd prefer and strongly recommend Jest)

**Chores**: Automatically running tests and code style checks in the CI is a bit _funky_ right now ;) Mostly due to the fact that there's both Jest and doctest in the mix, of course. However, there's more to do: npm dependencies are outdated, Node.js will have v16 as LTS version starting this October, etc. etc. etc.

=> What do you think? Are there things I've missed? Or do you have questions?

### PR DESCRIPTION
**Pull request by lvlte**
Full switch to ESM. 
Remove live code examples (either convert to Jest test or leave hints as a comment). 
Remove all console.log (except if encapsulated within a specific method/function).
Revise all algorithms logging results instead of returning them. 
...

Fixes #720

### CODE REVIEW

**Comment by raklaptudirm** [comment]
Is this done? If it is not, please convert the pr to draft.

**Comment by raklaptudirm** [comment]
@lvlte Please try to avoid using the jest mock functions. Remove the console logs wherever possible, and only use the mock functions where the console logs are a part of the solution.

**Comment by lvlte** [comment]
It was tedious but I think I'm finally done with this PR.

**Comment by lvlte** [comment]
Thanks, I've added the keyword in the PR description.

**Pull request merged**
