### PR TITLE
Wrapping the example matrix with outer array

### PR DESCRIPTION
**Pull request by tmkasun**
### Describe your change:

Without the outer array , given arrays are passed as 4 arguments to the `island` function

- [ ] Add an algorithm?
- [x] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

### Checklist:

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [ ] All new JavaScript files are placed inside an existing directory.
- [ ] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`UserProfile.js` is allowed but `userprofile.js`,`Userprofile.js`,`user-Profile.js`,`userProfile.js` are not
- [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by appgurueu — APPROVED** [review]
Actual tests would be preferable, but this is definitely an improvement.

**Review by raklaptudirm — CHANGES_REQUESTED** [review]
I think we would prefer to have the comments removed and replaced with actual jest tests.

**Comment by tmkasun** [comment]
Hi @raklaptudirm & @appgurueu ,

I have added a test file for `NumberOfIslands` algorithm, Please review and merge.

**Review by raklaptudirm — APPROVED** [review]

**Comment by tmkasun** [comment]
@appgurueu Kind reminder on this

**Review by appgurueu — CHANGES_REQUESTED** [review]
The tests have useless names ("Test Case <n>") currently. Either give them sensible names or move them all into one test block. Please inline to `expect(islands(graph)).toBe(n)`. You might even want to inline `graph` if you find that it doesn't hinder readability.
---

Side note: Why does "number of islands" expect strings; could you change it to use numbers instead?

**Review by appgurueu — APPROVED** [review]
(the test case names are pretty redundant though)

**Comment by tmkasun** [comment]
> (the test case names are pretty redundant though)

Yes true, But if I merge them together then it becomes a bit cluttered.

@raklaptudirm Can you please review and merge

**Review by raklaptudirm — APPROVED** [review]

**Pull request merged**
